### ISSUE TITLE
Updating NURBS WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility)

### ISSUE THREAD

**Issue by luzpaz** [microelly2/freecad-nurbs#4]
https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by luzpaz** [comment]
```
During initialization the error Missing parentheses in call to 'print'. Did you mean print("create toolbars-------------------------")? (<string>, line 900) occurred in /home/joel/.FreeCAD/Mod/nurbs/InitGui.py
Please look into the log file for further information
```

**Comment by Geoplace** [comment]
I also have the error.

The workbench load more or less ok but when try
Nurbs >Edit Draft Bspline

The report view shows
Running the Python command 'Nurbs_DraftBSpline Editor' failed:
Traceback (most recent call last):
  File "<string>", line 271, in Activated
  File "<string>", line 1, in <module>

Missing parentheses in call to 'print'. Did you mean print("huhuhuhsfsdfdf u")? (DraftBSplineEditor.py, line 83)Running the Python command 'Nurbs_DraftBSpline Editor' failed:
Traceback (most recent call last):
  File "<string>", line 271, in Activated
  File "<string>", line 1, in <module>

Missing parentheses in call to 'print'. Did you mean print("huhuhuhsfsdfdf u")? (DraftBSplineEditor.py, line 83)

OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Spanish/Mexico (es_MX)

**Comment by luzpaz** [comment]
@microelly2 quick question: what's the status on this ticket?

**Comment by microelly2** [comment]
The migration to python3 is more complex than only to replace some prints, it will take more time and I do not have time this spring and summer.

**Comment by MatLeb** [comment]
Hi Microelly2,

I came across your work looking for split views in FreeCad, and I saw your workspace feature with quadview in Nurbs, it's incredible. By the way thanks for your youtube videos (https://www.youtube.com/user/microelly/videos), it blows my mind to see what's possible with FreeCad.

I understood that there are some compatibility issues with recent versions of FreeCad, so I was just wondering if you plan to address those, in the futur (thinking about all the recent fusion to freecad migration)?
I don't know what's behind but I'm sure it's a big work... (it seems that some FreeCad developpers are able to get some patreon help by the way)

**Comment by luzpaz** [comment]
Someone may need to fork this workbench and port it, to get the functionality to work. We haven't seen @microelly2 in a while. We hope he's doing well. A lot of these issues are longstanding (while he was active). That would be a way forward.

**Comment by nighcoder** [comment]
If anyone wants to work on this project, you might want to look at my fork which moved the code to Python3. I can't remember about the Qt changes though, as I've lost interest in the project at that point,  so that might still need some working to do.
Also, you might want to check @galou's fork. He also worked on getting the plugin to Python3, I see in his PR.

**Comment by projectcad** [comment]
But  commands of your fork and @galou 's fork don't work in current FC version...same errors like in @microelly2 ...

**Comment by projectcad** [comment]
But commands of your fork and @galou 's fork doesnt work currently in current FC version...same errors like in @microelly2 ...

**Comment by projectcad** [comment]
I also tried it in Freecad 0.17( Python2, Qt4), but same errors...@galou @microelly2

**Comment by luzpaz** [comment]
https://github.com/microelly2/reconstruction/issues/2#issuecomment-808788245

**Comment by Patola** [comment]
Nobody has @microelly2's contact? His disappearance is concerning.

**Comment by luzpaz** [comment]
@Patola https://forum.freecadweb.org/viewtopic.php?f=8&t=55220
